default: &default
  adapter:            postgis
  encoding:           utf-8
  schema_search_path: 'public, postgis'
  pool:               <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: januus-exp_dev

test:
  <<: *default
  database: januus-exp_test

production:
  <<: *default
  url:      <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, 'postgis') %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
